services:
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U projectsprint_user -d projectsprint_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    build: ./
    command: python app/app.py
    volumes:
      - ./:/code
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  postgres_data:
